import type { OutcomeKind } from '../core/events/types.ts';

/**
 * SOUND, SYNTHESIZED
 *
 * Everything here is generated by the Web Audio API at the moment it is needed:
 * no files, no network requests, nothing to preload and nothing to 404 on a
 * bare deployment. For a game about pressure in a two-second window, audio is
 * the cheapest tension there is — a crowd that swells while the chance builds,
 * a clock you can hear draining, a commit you notice without looking at the
 * strip — and every one of those cues restates something ALREADY on screen.
 * Nothing is audible that is not also visible, so playing muted loses comfort,
 * never information. That is the same rule the keeper strip follows.
 *
 * THE CONTEXT IS CREATED LAZILY, on the first cue after a user gesture,
 * because browsers refuse audio before one. Every entry point that can make a
 * sound (playing a match, deciding) is behind at least one click, so in
 * practice the first cue always succeeds — but every method still fails silent
 * rather than loud: a game that cannot play audio should feel like a game with
 * the sound off, not a game with a broken speaker.
 */

/** How an outcome should sound, grouped: full detail would be seventeen jingles nobody could tell apart. */
type OutcomeVoice = 'goal' | 'woodwork' | 'good' | 'stopped' | 'lost' | 'quiet';

function outcomeVoice(kind: OutcomeKind): OutcomeVoice {
  switch (kind) {
    case 'goal':
      return 'goal';
    case 'post':
      return 'woodwork';
    case 'chanceCreated':
    case 'passCompleted':
    case 'dribbleSuccess':
    case 'crossCompleted':
    case 'ballWon':
      return 'good';
    case 'saved':
    case 'blocked':
    case 'deflected':
    case 'missed':
    case 'crossCleared':
      return 'stopped';
    case 'passIntercepted':
    case 'dribbleFailed':
    case 'turnover':
    case 'foulCommitted':
      return 'lost';
    case 'held':
      return 'quiet';
  }
}

class SoundEngine {
  /** Set from settings; every cue checks it, so muting needs no teardown. */
  enabled = true;

  private ctx: AudioContext | null = null;
  private master: GainNode | null = null;
  private crowdGain: GainNode | null = null;
  private crowdSource: AudioBufferSourceNode | null = null;
  /**
   * The last time the crowd reacted to a goal, in context time. A goal the
   * player scored roars from the resolution AND appears as a commentary line,
   * and both paths asking for a roar must produce one crowd, not an echo.
   */
  private lastRoarAt = -10;

  private ensure(): AudioContext | null {
    if (!this.enabled) return null;
    if (!this.ctx) {
      if (typeof AudioContext === 'undefined') return null;
      try {
        this.ctx = new AudioContext();
      } catch {
        return null;
      }
      this.master = this.ctx.createGain();
      this.master.gain.value = 0.5;
      this.master.connect(this.ctx.destination);
    }
    // Suspended is the normal state before a gesture; resuming is fire-and-forget
    // because a cue that arrives one frame late is better than one that throws.
    if (this.ctx.state === 'suspended') void this.ctx.resume();
    return this.ctx;
  }

  /** One enveloped oscillator note. Everything melodic is built from this. */
  private tone(
    frequency: number,
    options: {
      type?: OscillatorType;
      at?: number;
      duration?: number;
      gain?: number;
      /** Glide the pitch here over the duration, for whistles and falls. */
      to?: number;
    } = {},
  ): void {
    const ctx = this.ensure();
    if (!ctx || !this.master) return;
    const { type = 'sine', at = 0, duration = 0.15, gain = 0.15, to } = options;
    const start = ctx.currentTime + at;
    const osc = ctx.createOscillator();
    osc.type = type;
    osc.frequency.setValueAtTime(frequency, start);
    if (to !== undefined) osc.frequency.exponentialRampToValueAtTime(Math.max(1, to), start + duration);
    const env = ctx.createGain();
    env.gain.setValueAtTime(0, start);
    env.gain.linearRampToValueAtTime(gain, start + 0.01);
    env.gain.exponentialRampToValueAtTime(0.001, start + duration);
    osc.connect(env);
    env.connect(this.master);
    osc.start(start);
    osc.stop(start + duration + 0.05);
  }

  /** A burst of filtered noise — thuds, impacts, and the crowd's raw material. */
  private noiseBurst(
    options: { at?: number; duration?: number; gain?: number; frequency?: number; rise?: number } = {},
  ): void {
    const ctx = this.ensure();
    if (!ctx || !this.master) return;
    const { at = 0, duration = 0.3, gain = 0.15, frequency = 600, rise = 0.02 } = options;
    const start = ctx.currentTime + at;
    const source = ctx.createBufferSource();
    source.buffer = this.noiseBuffer(ctx);
    source.loop = true;
    const filter = ctx.createBiquadFilter();
    filter.type = 'bandpass';
    filter.frequency.value = frequency;
    filter.Q.value = 0.9;
    const env = ctx.createGain();
    env.gain.setValueAtTime(0, start);
    env.gain.linearRampToValueAtTime(gain, start + rise);
    env.gain.exponentialRampToValueAtTime(0.001, start + duration);
    source.connect(filter);
    filter.connect(env);
    env.connect(this.master);
    source.start(start);
    source.stop(start + duration + 0.05);
  }

  private cachedNoise: AudioBuffer | null = null;
  private noiseBuffer(ctx: AudioContext): AudioBuffer {
    if (this.cachedNoise) return this.cachedNoise;
    const buffer = ctx.createBuffer(1, ctx.sampleRate * 2, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;
    this.cachedNoise = buffer;
    return buffer;
  }

  // ------------------------------------------------------------ ambience ---

  /**
   * The crowd bed: looped noise through a low filter, quiet by default.
   * Idempotent, so the match screen can call it without checking.
   */
  startAmbience(): void {
    const ctx = this.ensure();
    if (!ctx || !this.master || this.crowdSource) return;
    const source = ctx.createBufferSource();
    source.buffer = this.noiseBuffer(ctx);
    source.loop = true;
    const filter = ctx.createBiquadFilter();
    filter.type = 'lowpass';
    filter.frequency.value = 500;
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, ctx.currentTime);
    gain.gain.linearRampToValueAtTime(0.04, ctx.currentTime + 1.5);
    source.connect(filter);
    filter.connect(gain);
    gain.connect(this.master);
    source.start();
    this.crowdSource = source;
    this.crowdGain = gain;
  }

  stopAmbience(): void {
    const ctx = this.ctx;
    if (!ctx || !this.crowdSource || !this.crowdGain) return;
    const source = this.crowdSource;
    this.crowdGain.gain.cancelScheduledValues(ctx.currentTime);
    this.crowdGain.gain.setValueAtTime(this.crowdGain.gain.value, ctx.currentTime);
    this.crowdGain.gain.linearRampToValueAtTime(0, ctx.currentTime + 0.8);
    window.setTimeout(() => source.stop(), 900);
    this.crowdSource = null;
    this.crowdGain = null;
  }

  /**
   * How awake the crowd is, 0-1. The overlay raises it as a chance builds and
   * the match screen lets it settle back down between moments.
   */
  crowd(level: number): void {
    const ctx = this.ctx;
    if (!ctx || !this.crowdGain) return;
    const target = 0.04 + Math.max(0, Math.min(1, level)) * 0.1;
    this.crowdGain.gain.cancelScheduledValues(ctx.currentTime);
    this.crowdGain.gain.setValueAtTime(this.crowdGain.gain.value, ctx.currentTime);
    this.crowdGain.gain.linearRampToValueAtTime(target, ctx.currentTime + 0.8);
  }

  /** The crowd erupting — a goal, whoever scored it. Debounced; see lastRoarAt. */
  roar(): void {
    const ctx = this.ensure();
    if (!ctx) return;
    if (ctx.currentTime - this.lastRoarAt < 2.5) return;
    this.lastRoarAt = ctx.currentTime;
    this.noiseBurst({ duration: 1.6, gain: 0.35, frequency: 400, rise: 0.12 });
    this.noiseBurst({ at: 0.05, duration: 1.2, gain: 0.2, frequency: 900, rise: 0.15 });
  }

  /** The crowd deflating — a chance gone, or a goal at the wrong end. */
  groan(): void {
    this.noiseBurst({ duration: 0.7, gain: 0.12, frequency: 300, rise: 0.08 });
    this.tone(180, { type: 'sine', duration: 0.5, gain: 0.05, to: 120 });
  }

  // ----------------------------------------------------- moment-by-moment ---

  /** A build-up beat landing: the softest cue there is, one per line of story. */
  beat(): void {
    this.tone(220, { type: 'triangle', duration: 0.07, gain: 0.05 });
  }

  /** The options appearing: a short rise, because something just opened up. */
  reveal(): void {
    this.tone(440, { type: 'triangle', duration: 0.09, gain: 0.09 });
    this.tone(660, { type: 'triangle', at: 0.09, duration: 0.12, gain: 0.09 });
  }

  /**
   * The decision clock, twice a second, rising in pitch and weight as the
   * window drains. Never played at the untimed pace — a clock you can hear is
   * exactly the pressure that setting removes.
   */
  clockTick(urgency: number): void {
    const u = Math.max(0, Math.min(1, urgency));
    this.tone(700 + u * 500, { type: 'square', duration: 0.035, gain: 0.025 + u * 0.05 });
  }

  /** The keeper committing — the one fact worth interrupting the ears for. */
  keeperCommit(): void {
    this.tone(880, { type: 'sawtooth', duration: 0.14, gain: 0.1, to: 520 });
  }

  /** A decision made: one clean click, confirmation and nothing more. */
  choose(): void {
    this.tone(1200, { type: 'square', duration: 0.045, gain: 0.07 });
  }

  /** The window expiring with no decision: a fall, because that is what it is. */
  expire(): void {
    this.tone(400, { type: 'sawtooth', duration: 0.3, gain: 0.09, to: 150 });
  }

  /** Kick-off and full time. One peep starts a match; three end it. */
  whistle(peeps = 1): void {
    for (let i = 0; i < peeps; i++) {
      this.tone(2100, { type: 'square', at: i * 0.35, duration: i === peeps - 1 ? 0.4 : 0.15, gain: 0.06 });
      this.tone(2350, { type: 'square', at: i * 0.35, duration: i === peeps - 1 ? 0.4 : 0.15, gain: 0.03 });
    }
  }

  /**
   * How the moment resolved — the BALL'S own noise, not the crowd's.
   *
   * The two used to be one cue, which meant a goal roared at the instant of
   * contact and a save groaned before the ball had finished travelling. They
   * are separate now: this fires on the impact frame, and `reaction` follows a
   * beat later, because a crowd takes a moment to decide what it has seen. See
   * ui/crowdReaction.ts for who decides which reaction.
   */
  outcome(kind: OutcomeKind): void {
    switch (outcomeVoice(kind)) {
      case 'goal':
        this.tone(523, { type: 'triangle', duration: 0.12, gain: 0.12 });
        this.tone(659, { type: 'triangle', at: 0.11, duration: 0.12, gain: 0.12 });
        this.tone(784, { type: 'triangle', at: 0.22, duration: 0.3, gain: 0.14 });
        return;
      case 'woodwork':
        this.tone(160, { type: 'square', duration: 0.09, gain: 0.16 });
        this.noiseBurst({ duration: 0.06, gain: 0.1, frequency: 2500 });
        return;
      case 'good':
        this.tone(523, { type: 'triangle', duration: 0.09, gain: 0.09 });
        this.tone(784, { type: 'triangle', at: 0.09, duration: 0.14, gain: 0.09 });
        return;
      case 'stopped':
        this.noiseBurst({ duration: 0.12, gain: 0.14, frequency: 250 });
        return;
      case 'lost':
        this.noiseBurst({ duration: 0.15, gain: 0.12, frequency: 200 });
        this.tone(220, { type: 'sine', duration: 0.25, gain: 0.07, to: 140 });
        return;
      case 'quiet':
        this.tone(392, { type: 'triangle', duration: 0.08, gain: 0.05 });
        return;
    }
  }

  /** Applause: many short, bright noise bursts, unevenly spaced. */
  private applause(duration: number, gain: number): void {
    for (let i = 0; i < Math.round(duration * 22); i++) {
      this.noiseBurst({
        at: i * 0.045 + Math.random() * 0.03,
        duration: 0.05,
        gain: gain * (0.5 + Math.random() * 0.5),
        frequency: 1800 + Math.random() * 1800,
        rise: 0.004,
      });
    }
  }

  /**
   * BOOING, THE WAY A EUROPEAN GROUND ACTUALLY DOES IT — whistles.
   *
   * Not a cartoon "boo": a dozen shrill, detuned, badly-timed whistles over a
   * low rumble of discontent, which is what a crowd that has just watched a
   * sitter go wide actually sounds like.
   */
  private whistles(): void {
    for (let i = 0; i < 11; i++) {
      const at = Math.random() * 0.5;
      const pitch = 2000 + Math.random() * 900;
      this.tone(pitch, {
        type: 'square',
        at,
        duration: 0.16 + Math.random() * 0.22,
        gain: 0.018 + Math.random() * 0.016,
        to: pitch * (0.9 + Math.random() * 0.25),
      });
    }
    this.noiseBurst({ duration: 1.1, gain: 0.1, frequency: 260, rise: 0.1 });
  }

  /**
   * WHAT THE GROUND MAKES OF IT.
   *
   * Fired a beat after the impact, and only for the moments that earn one —
   * `crowdReaction` returns silence for routine football, and silence here is
   * a feature: a crowd that cheers a sideways pass has nothing left for a goal.
   */
  reaction(mood: 'ovation' | 'cheer' | 'sigh' | 'jeer' | 'silent'): void {
    switch (mood) {
      case 'ovation':
        this.roar();
        this.applause(1.8, 0.05);
        // The swell underneath it: a rising filtered wash, the sound of a
        // stand getting to its feet.
        this.noiseBurst({ at: 0.1, duration: 2.2, gain: 0.16, frequency: 700, rise: 0.5 });
        return;
      case 'cheer':
        this.noiseBurst({ duration: 0.8, gain: 0.16, frequency: 420, rise: 0.09 });
        this.applause(0.7, 0.035);
        return;
      case 'sigh':
        this.groan();
        return;
      case 'jeer':
        this.groan();
        this.whistles();
        return;
      case 'silent':
        return;
    }
  }
}

/**
 * One engine for the whole game, exported as a value rather than a class:
 * audio is a property of the machine playing it, like the save, and two
 * screens each owning half an AudioContext would fight over the crowd.
 */
export const sound = new SoundEngine();
